---
title: "Simulations"
output:
  pdf_document:
    template: notes/style.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, message = FALSE, warning = FALSE, fig.width = 5, fig.height = 2)
```

```{r}
library("MASS")
library("MCMCpack")
library("dplyr")
library("ggplot2")
library("ggraph")
library("magrittr")
library("pdist")
library("purrr")
library("stringr")
library("superheat")
library("tibble")
library("tidygraph")
library("tidyr")
library("tidytext")
library("topicmodels")
source("R_LSY/align_topics_all_functions.R")
source("simulation_functions.R")
set.seed(1234)
(theme_minimal() + 
  theme(
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_rect(fill = NA, color = "#0c0c0c", size = 0.6),
    legend.position = "bottom"
  )) %>%
  theme_set()
```

```{r}
K <- 5
V <- 250
N <- 100
lambdas <- list(beta = 0.5, gamma = 0.1, nu = 0.1)

sim_data <- simulate_gradient(N, K, V, lambdas, alpha = 0.7)
alignment <- vis_wrapper(sim_data$x, ceiling(1.5 * K))
alignment$p2
```


```{r}
sim_data <- simulate_gradient(N, K, V, lambdas, alpha = 0.2)
alignment <- vis_wrapper(sim_data$x, ceiling(1.5 * K))
alignment$p2
```

```{r}
#N <- 250
#K <- 5
#V <- 750
N <- 100
V <- 250
K <- 4
sim_data <- equivalence_data(N, V, K, list(beta = .5, gamma = 0.1), subset_size = 75)
alignment <- vis_wrapper(sim_data$x, ceiling(1.5 * K))
```

```{r, fig.height = 2, fig.width = 7}
superheat(map(sim_data$B_tilde, ~ as_tibble(.)) %>% bind_rows(), legend = FALSE)
```

```{r, fig.height = 3, fig.width = 6}
alignment$p2
```

Compare the true with the estimated betas, before any perturbation.
```{r}
ordered_topics <- alignment$alignment$beta_alignment %>%
  select(m, k_LDA, topic) %>%
  unique()

alignment$fits$betas <- alignment$fits$betas %>%
  left_join(ordered_topics) %>%
  select(m, K, k_LDA, topic, w, b)
```

```{r, fig.width = 2, fig.height = 8}
beta_hats <- alignment$fits$betas %>%
  pivot_wider(m:topic, names_from = w, values_from = b)
beta_hats_mat <- beta_hats %>%
  select(matches("[0-9]+")) %>%
  as.matrix()
```

Now include the perturbed betas in the plot, and compare with estimates at a
more refined $K$.

```{r, fig.width = 2, fig.height = 8}
similarity <- cosine_similarity(beta_hats_mat, do.call(rbind, sim_data$B_tilde)) %>%
  as_tibble() %>%
  bind_cols(beta_hats %>% select(K, topic)) %>%
  pivot_longer(starts_with("V"), names_to = "beta", values_to = "sim") %>%
  mutate(
    beta = str_replace(beta, "V", ""),
    beta = str_pad(beta, 2)
  ) %>%
  filter(K < max(K))

ggplot(similarity, aes(beta, topic)) +
  geom_tile(aes(fill = sqrt(sim))) +
  scale_fill_distiller(direction = 1) +
  scale_x_discrete(expand = c(0, 0)) +
  scale_y_discrete(expand = c(0, 0)) +
  facet_grid(K ~ ., scale = "free_y", space = "free")
```

```{r, fig.width = 6, fig.height = 3}
K <- 10
N <- rep(25, 6)
V <- 200
sim_data <- environment_shifts(N, K, K, list(pool = 0.2, e = rep(.5, length(N)), beta = 1))

sim_data$gammas %>%
  pivot_longer(-environment, names_to = "k_LDA", values_to = "g") %>%
  ggplot(aes(k_LDA, log(g))) +
  geom_point(alpha = 0.4, size = 0.9, position = position_jitter(w = 0.1)) +
  ylim(-10, 0) +
  facet_wrap(~ environment)
```

```{r}
x_pool <- sim_data$x %>%
  select(-environment) %>%
  mutate(ix = row_number()) %>%
  column_to_rownames("ix")
pooled_fit <- LDA(x = x_pool, k = K)
```

```{r}
fits <- sim_data$x %>%
  split(.$environment) %>%
  map(~ LDA(x = select(., -environment), k = 4))
```

The pooled fit.

```{r}
memberships <- tidy(pooled_fit, "gamma") %>%
  left_join(
    sim_data$x %>%
      mutate(document = as.character(row_number())) %>%
      select(document, environment)
  )
hclust_result <- hclust(dist(pooled_fit@gamma))
document_order <- pooled_fit@documents[hclust_result$order]
memberships <- memberships %>%
  mutate(
    document = factor(document, levels = document_order),
    topic = as.factor(topic)
  )
```

```{r, fig.height = 8, fig.width = 5}
ggplot(memberships, aes(gamma, document, fill = topic, col = topic)) +
  geom_col(position = position_stack()) +
  facet_grid(environment ~ ., scales = "free", space = "free") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_color_brewer(palette = "Set3", guide = FALSE) +
  scale_fill_brewer(palette = "Set3") +
  labs(x = "Topic Membership", y = "Sample", fill = "Topic") +
  theme(
    strip.text.y = element_text(size = 8, angle = 0),
    axis.text.y = element_blank(),
  )
```

Instead consider alignment across environments.

```{r}
betas <- map(fits, ~ .@beta)
masses <- map(fits, ~ matrix(colSums(.@gamma), ncol = 1))
alignments <- align_pairs(betas, masses, reg = 2e-2)
```

```{r, fig.height = 4, fig.width = 6}
G <- graph_data(alignments, masses)
ggraph(G, "fr") +
  geom_edge_link(aes(width = norm_weight, alpha = norm_weight)) +
  geom_node_label(aes(label = k, fill = group, size = mass)) +
  scale_edge_width(range = c(0, 3)) +
  scale_fill_brewer(palette = "Set2") +
  guides(fill = guide_legend(override.aes = aes(label = ""))) +
  scale_size(range = c(.1, 5), guide = FALSE)
```

```{r}
fits[[5]]@beta[4, ]
fits[[3]]@beta[4, ]
```
```{r}
betas <- c(map(fits, ~ .@beta), list(log(sim_data$B)))
masses <- c(
  map(fits, ~ matrix(colSums(.@gamma), ncol = 1)),
  list(matrix(colSums(select(sim_data$gammas, -environment)), ncol = 1))
) %>%
  map(~ . / sum(.))

alignments <- align_pairs(betas, masses, reg = 2e-2)
G <- graph_data(alignments, masses)
```

```{r, fig.height = 3, fig.width = 6}
G <- G %>%
  mutate(type = group == "7")

ggraph(G, "bipartite") +
  geom_edge_link(aes(width = norm_weight, alpha = norm_weight)) +
  geom_node_label(aes(label = k, fill = group, size = mass)) +
  scale_edge_width(range = c(0, 3)) +
  scale_fill_brewer(palette = "Set2") +
  guides(fill = guide_legend(override.aes = aes(label = ""))) +
  scale_size(range = c(.1, 5), guide = FALSE)
```
