---
title: "Simulations"
output:
  pdf_document:
    template: notes/style.tex
params:
  out_dir: "/Users/ksankaran/Desktop/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, message = FALSE, warning = FALSE, fig.width = 5, fig.height = 2)
```

```{r}
library("MCMCpack")
library("dplyr")
library("ggplot2")
library("ggraph")
library("magrittr")
library("pdist")
library("purrr")
library("stringr")
library("tibble")
library("tidygraph")
library("tidyr")
library("tidytext")
library("topicmodels")
source("../R_LSY/align_topics_all_functions.R")
source("simulation_functions.R")
set.seed(1234)
(theme_minimal() + 
  theme(
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_rect(fill = NA, color = "#0c0c0c", size = 0.6),
    legend.position = "bottom"
  )) %>%
  theme_set()
fig <- function(p) { file.path(params$out_dir, p) }
```


```{r, fig.width = 6, fig.height = 3}
K <- 10
N <- rep(500, 6)
V <- 50
sim_data <- environment_shifts(N, K, K, list(pool = 0.1, e = rep(1, length(N)), beta = .3))

gamma_data <- sim_data$gammas %>%
  pivot_longer(-environment, names_to = "k_LDA", values_to = "g") %>%
  mutate(
    k_LDA = str_replace(k_LDA, "V", ""),
    k_LDA = factor(k_LDA, levels = 1:K)
  ) 

p <- ggplot(gamma_data, aes(k_LDA, log(g))) +
  geom_point(alpha = 0.4, size = 0.9, position = position_jitter(w = 0.1)) +
  ylim(-10, 0) +
  labs(
    y = expression(log(gamma[k])),
    x = "topic"
  ) +
  facet_wrap(~ environment)
ggsave(fig("environment_gammas.png"), p, dpi = 900, width = 6, height = 3)
```

```{r}
x_pool <- sim_data$x %>%
  select(-environment) %>%
  mutate(ix = row_number()) %>%
  column_to_rownames("ix")
pooled_fit <- LDA(x = x_pool, k = K)
```

```{r}
fits <- sim_data$x %>%
  split(.$environment) %>%
  map(~ LDA(x = select(., -environment), k = 4))
```

The pooled fit.

```{r}
memberships <- tidy(pooled_fit, "gamma") %>%
  left_join(
    sim_data$x %>%
      mutate(document = as.character(row_number())) %>%
      select(document, environment)
  )

hclust_result <- hclust(dist(pooled_fit@gamma))
document_order <- pooled_fit@documents[hclust_result$order]
memberships <- memberships %>%
  mutate(
    document = factor(document, levels = document_order),
    topic = as.factor(topic)
  )
```

```{r, fig.height = 8, fig.width = 5}
ggplot(memberships, aes(gamma, document, fill = topic, col = topic)) +
  geom_col(position = position_stack()) +
  facet_grid(environment ~ ., scales = "free", space = "free") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_color_brewer(palette = "Set3", guide = FALSE) +
  scale_fill_brewer(palette = "Set3") +
  labs(x = "Topic Membership", y = "Sample", fill = "Topic") +
  theme(
    strip.text.y = element_text(size = 12, angle = 0),
    axis.text.y = element_blank(),
  )

ggsave(fig("environment_structure_plot.png"), p, dpi = 900, height = 7, width = 6)
```

Instead consider alignment across environments.

```{r}
betas <- map(fits, ~ as_tibble(.@beta))
masses <- map(fits, ~ matrix(colSums(.@gamma), ncol = 1))
alignments <- align_pairs(betas, masses, reg = 2e-3)
```


```{r, fig.height = 4.5, fig.width = 5.5}
G <- graph_data(alignments, masses)
ggraph(G, "stress") +
  geom_edge_link(aes(width = weight, alpha = weight)) +
  geom_node_label(aes(label = k, fill = group, size = mass)) +
  scale_edge_width(range = c(0, 2)) +
  scale_edge_alpha(range = c(0, .9)) +
  scale_fill_brewer(palette = "Set2") +
  guides(fill = guide_legend(override.aes = aes(label = ""))) +
  coord_fixed() +
  scale_size(range = c(.1, 5), guide = FALSE)
```

```{r, fig.height = 10, fig.width = 10}
cols <- c('#f6eff7','#d0d1e6','#a6bddb','#67a9cf','#3690c0','#02818a','#016450')
G %>%
  activate(edges) %>%
  as_tibble() %>% 
  select(-weight) %>%
  pivot_wider(names_from = "to", values_from = "norm_weight", values_fill = 0) %>%
  column_to_rownames("from") %>%
  superheat(pretty.order.rows = TRUE, pretty.order.cols = TRUE, heat.pal = cols)
```

```{r}
betas <- c(map(fits, ~ .@beta), list(log(sim_data$B))) %>%
  map(~ as_tibble(.))
masses <- c(
  map(fits, ~ matrix(colSums(.@gamma), ncol = 1)),
  list(matrix(colSums(select(sim_data$gammas, -environment)), ncol = 1))
) %>%
  map(~ . / sum(.))
alignments <- align_pairs(betas, masses, reg = 5e-3) %>%
  filter(group2 == length(N) + 1)
G <- graph_data(alignments, masses)
```

```{r, fig.height = 3, fig.width = 6}
G <- G %>%
  mutate(type = group == "7")

ggraph(G, "bipartite") +
  #geom_edge_link(aes(width = norm_weight, alpha = norm_weight)) +
  geom_edge_diagonal(aes(width = weight, alpha = weight)) +
  geom_node_label(aes(label = k, fill = group, size = mass)) +
  scale_edge_width(range = c(0, 1.2)) +
  scale_edge_alpha(range = c(0, .8)) +
  scale_fill_brewer(palette = "Set2") +
  guides(fill = guide_legend(override.aes = aes(label = ""))) +
  labs(width = "Normalized weight", col = "Environment") +
  scale_size(range = c(.1, 5), guide = FALSE)
ggsave(fig("environments_bipartite.png"), dpi = 900, width = 6, height = 3)
```


