---
title: "Simulations"
output:
  pdf_document:
    template: notes/style.tex
params:
  out_dir: "/Users/ksankaran/Desktop/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, message = FALSE, warning = FALSE, fig.width = 5, fig.height = 2)
```

```{r}
library("MCMCpack")
library("dplyr")
library("ggplot2")
library("magrittr")
library("pdist")
library("purrr")
library("stringr")
library("tibble")
library("tidyr")
library("tidytext")
library("topicmodels")
source("../R_LSY/align_topics_all_functions.R")
source("simulation_functions.R")
set.seed(1234)
(theme_minimal() + 
  theme(
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_rect(fill = NA, color = "#0c0c0c", size = 0.6),
    legend.position = "bottom"
  )) %>%
  theme_set()
fig <- function(p) { file.path(params$out_dir, p) }
```

```{r}
V <- 100
lambdas <- list(beta = 1, alpha = c(1, 1), alpha_shared = 2)
gammas <- multimodal_gammas(100, c(3, 3), lambdas$alpha, k_shared = 2, alpha_shared = lambdas$alpha_shared)
betas <- map(gammas, ~ rdirichlet(ncol(.), rep(lambdas$beta, V)))
```

```{r}
x <- map(seq_along(gammas), ~ simulate_lda(betas[[.]], gammas[[.]]))
fits <- map(x, ~ LDA(x = ., k = 7))
gamma_hat <- map(list(fits[[1]]@gamma, fits[[2]]@gamma), ~ as_tibble(.)) %>%
  bind_rows(.id = "m")
```

```{r, fig.width = 4, fig.height = 4.5}
weights <- .gamma_weights(fits[[1]]@gamma, fits[[2]]@gamma)
scatter_data <- multimodal_scatter_data(gamma_hat, weights)
ggplot(scatter_data, aes(gamma_source, gamma_target)) +
  geom_abline(size = 0.5, col = "#d3d3d3") +
  geom_point(aes(col = weight), alpha = 0.8, size = .2) +
  facet_grid(source ~ target) +
  coord_fixed() +
  scale_color_viridis_c() +
  theme(axis.text = element_text(size = 5))
ggsave(fig("multimodal_memberships_gamma.png"), width = 4, height = 4.5, dpi = 600)
```
```{r}
weights <- cor(fits[[1]]@gamma, fits[[2]]@gamma) %>%
  .weights_to_df()
scatter_data <- multimodal_scatter_data(gamma_hat, weights)
ggplot(scatter_data, aes(gamma_source, gamma_target)) +
  geom_abline(size = 0.5, col = "#d3d3d3") +
  geom_point(aes(col = weight), alpha = 0.8, size = .2) +
  facet_grid(source ~ target) +
  coord_fixed() +
  scale_color_viridis_c() +
  theme(axis.text = element_text(size = 5))
ggsave(fig("multimodal_memberships_corr.png"), width = 4, height = 4.5, dpi = 600)
```

```{r, fig.height = 6, fig.width = 6}
masses <- gamma_hat %>%
  pivot_longer(-m, names_to = "k_LDA", values_to = "g") %>%
  mutate(k_LDA = str_replace(k_LDA, "V", "")) %>%
  .topic_weights()

gamma_list <- map(list(fits[[1]]@gamma, fits[[2]]@gamma), ~ as_tibble(t(.)))
weights <- .beta_weights(gamma_list, masses) %>%
  rename(source = k, target = k_next)
scatter_data <- multimodal_scatter_data(gamma_hat, weights)
ggplot(scatter_data, aes(gamma_source, gamma_target)) +
  geom_abline(size = 0.5, col = "#d3d3d3") +
  geom_point(aes(col = weight), alpha = 0.8, size = .2) +
  facet_grid(source ~ target) +
  coord_fixed() +
  scale_color_viridis_c() +
  theme(axis.text = element_text(size = 5))
ggsave(fig("multimodal_memberships_beta.png"), width = 4, height = 4.5, dpi = 600)
```
```{r}
cor(fits[[1]]@gamma, gammas[[1]]) %>% round(3)
cor(fits[[2]]@gamma, gammas[[2]]) %>% round(3)
```
