---
title: "Simulations"
output:
  pdf_document:
    template: ../notes/style.tex
params:
  out_dir: "/Users/kris/Desktop/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, message = FALSE, warning = FALSE, fig.width = 5, fig.height = 2)
```

```{r}
library("MCMCpack")
library("dplyr")
library("ggplot2")
library("magrittr")
library("pdist")
library("purrr")
library("stringr")
library("superheat")
library("tibble")
library("tidyr")
library("tidytext")
library("topicmodels")
source("../R_LSY/align_topics_all_functions.R")
source("simulation_functions.R")
set.seed(12345)
(theme_minimal() + 
  theme(
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_rect(fill = NA, color = "#0c0c0c", size = 0.6),
    legend.position = "bottom"
  )) %>%
  theme_set()
fig <- function(p) { file.path(params$out_dir, p) }
```

```{r}
K <- 4
V <- 250
N <- 100
lambdas <- list(beta = 0.5, gamma = 0.1, nu = 0.1)
sim_data <- simulate_gradient(N, K, V, lambdas, alpha = 1)
fits <- run_lda_models(x, c(2, 4, 6))
```

```{r}
gamma_hats_wide <- fits$gammas %>%
  unite(m_k, c("m", k_LDA)) %>%
  select(d, m_k, g) %>%
  pivot_wider(-m_k, names_from = m_k, values_from = g)
d_order <- hclust(dist(gamma_hats_wide[, -1]))$order
gamma_hats <- fits$gammas %>%
  mutate(d = factor(d, levels = gamma_hats_wide$d[d_order]))
```


```{r}
ggplot(gamma_hats %>% filter(m != 1)) +
  geom_tile(aes(k_LDA, d, fill = g)) +
  facet_grid(~ m, scale = "free_x", space = "free")
```

```{r}
gamma_hats <- fits$gammas %>%
  split(.$m) %>%
  map(~ select(., -m, -K)) %>%
  map(~ rename(., doc = d)) %>%
  map(~ pivot_wider(., doc, names_from = k_LDA, values_from = g)) %>%
  map(~ column_to_rownames(., "doc") %>% as.matrix())
```


```{r}
beta_hats <- fits$betas %>%
  split(.$m) %>%
  map(~ select(., -m, -K)) %>%
  map(~ rename(., word = w)) %>%
  map(~ pivot_wider(., word, names_from = k_LDA, values_from = b)) %>%
  map(~ column_to_rownames(., "word") %>% as.matrix())
```

```{r}
w1 <- align_sequence(gamma_hats, cosine_similarities)
w2 <- align_sequence(gamma_hats, transport_similarities)
w1
w2
```
