---
title: "Simulations"
params:
  out_dir: "/Users/kris/Desktop/"
  method: "product"
  id: 1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, message = FALSE, warning = FALSE, fig.width = 5, fig.height = 2)
```

```{r}
library("MCMCpack")
library("alto")
library("readr")
source("simulation_functions.R")
set.seed(params$id)
(theme_minimal() + 
  theme(
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_rect(fill = NA, color = "#0c0c0c", size = 0.6),
    legend.position = "bottom"
  )) %>%
  theme_set()
```

```{r}
K <- 5
V <- 1000
N <- 100
lambdas <- list(beta = 0.5, gamma = 0.5, nu = 0.1, count=1e4)
n_models <- 10

fit_wrapper <- function(x, n_models) {
  lda_params <- map(1:n_models, ~ list(k = .))
  names(lda_params) <- str_c("K", 1:n_models)
  lda_models <- run_lda_models(sim_data$x, lda_params, reset = TRUE)
  align_topics(lda_models, method = params$method)
}
```

```{r}
sim_data <- simulate_gradient(N, K, V, lambdas, alpha = 1, lambda = lambdas$count)
fit_wrapper(sim_data$x, n_models) %>%
  save(file = str_c("alignment-", params$id, "-1.rda"))
```

```{r}
sim_data <- simulate_gradient(N, K, V, lambdas, alpha = 0, lambda = lambdas$count)
fit_wrapper(sim_data$x, n_models) %>%
  save(file = str_c("alignment-", params$id, "-0.rda"))
```

```{r}
stability <- list()
refinement <- list()
key_topics <- list()
alphas <- seq(0, 1, length.out = 20)
for (i in seq_along(alphas)) {
  sim_data <- simulate_gradient(N, K, V, lambdas, alpha = alphas[i])
  alignment <- fit_wrapper(sim_data$x, n_models)
  stability[[i]] <- alto:::compute_stability_along_branches(alignment@weights)
  refinement[[i]] <- alto:::compute_refinement_scores(alignment@weights)
  key_topics[[i]] <- alto:::compute_number_of_key_topics(alignment@weights)
}

bind_and_write <- function(scores, out_name) {
  bind_rows(scores, .id = "alpha") %>%
    mutate(alpha = alphas[as.integer(alpha)]) %>%
    write_csv(file = out_name)
}

bind_and_write(stability, str_c("stability-", params$id, ".csv"))
bind_and_write(refinement, str_c("refinement-", params$id, ".csv"))
bind_and_write(key_topics, str_c("key_topics-", params$id, ".csv"))
```
