---
title: "True LDA Simulation"
params:
  out_dir: "."
  method: "transport"
  id: 1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, message = FALSE, warning = FALSE, fig.width = 5, fig.height = 2)
```

```{r}
library("MCMCpack")
library("alto")
library("dplyr")
library("readr")
library("ggplot2")
source("simulation_functions.R")
library("stringr")
library("purrr")
set.seed(params$id)
(theme_minimal() +
  theme(
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_rect(fill = NA, color = "#0c0c0c", size = 0.6),
    legend.position = "bottom"
  )) %>%
  theme_set()
```

```{r}
K <- 5
V <- 1000
N <- 100
n_models <- 10
lambdas <- list(beta = 0.5, gamma = 0.5, count = 1e4)

betas <- rdirichlet(K, rep(lambdas$beta, V))
gammas <- rdirichlet(N, rep(lambdas$gamma, K))
x <- simulate_lda(betas, gammas, lambda = lambdas$count)

lda_params <- map(1:n_models, ~ list(k = .))
names(lda_params) <- str_c("K", 1:n_models)
lda_models <- run_lda_models(x, lda_params, reset = TRUE)
```

```{r}
alignment <- align_topics(lda_models, method = params$method)
plot(alignment)
plot_beta(alignment, c(2, 4))
```

```{r}
stability <- alto:::compute_stability_along_branches(alignment@weights) %>%
  mutate(id = params$id)
ggplot(stability, aes(m, stability)) +
  geom_line(aes(group = branch), alpha = 0.5)
```

```{r}
refinement <- alto:::compute_refinement_scores(alignment@weights) %>%
  filter(m != str_c("K", n_models)) %>%
  mutate(id = params$id)
ggplot(refinement) +
  geom_point(aes(m, refinement_score)) +
  scale_y_log10()
```

```{r}
key_topics <- alto:::compute_number_of_key_topics(alignment@weights, T) %>%
  filter(m != str_c("K", n_models)) %>%
  mutate(id = params$id)
```

```{r}
write_csv(key_topics, file.path(params$out_dir, str_c("key_topics-", params$method, "-", params$id, ".csv")))
write_csv(refinement, file.path(params$out_dir, str_c("refinement-", params$method, "-", params$id, ".csv")))
write_csv(stability, file.path(params$out_dir, str_c("stability-", params$method, "-", params$id, ".csv")))
```
