---
title: "Visualize Strain Switching Results"
output: html_notebook
params:
    results_dir: "results/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, message = FALSE, warning = FALSE, fig.width = 5, fig.height = 2)
```

```{r}
library(alto)
library(dplyr)
library(ggplot2)
library(readr)
library(tibble)
library(purrr)
library(stringr)
library(tidyr)
source("simulation_functions.R")
source("visualization_functions.R")
my_theme()
```

The simulation results we're working with are saved
[here](https://uwmadison.box.com/shared/static/accan0ji43d7l97bia2fa9ai5zu826xm.gz).
If we download that file, unzip it, and unzip all its contents, we should see
the directories and files that are referred to in this rmarkdown. Specifically,
we could run,
```
curl -L https://uwmadison.box.com/shared/static/accan0ji43d7l97bia2fa9ai5zu826xm.gz > results.tar.gz
tar -zxvf results.gz
cd results # set this to results_dir in the rmarkdown YAML
for f in $(ls *.tar.gz); do tar -zxvf $f; done
```
in our terminal.

### Strain Switching

```{r}
equiv_dir <- file.path(params$results, "equivalence")
similarities <- read_and_process("*similarities*", c("rep", "S"), equiv_dir)
```

```{r}
exper <- get(load(file.path(equiv_dir, "exper-transport_230_12_250_1000_5.rda")))
sim_data <- exper[[1]]
fit <- exper[[2]]
plot(fit) +
  labs(x = "K Topics") +
  labs(x = "K Topics") +
  theme(
    axis.text.y = element_blank(),
    axis.text.x = element_text(size = 10),
    axis.title.x = element_text(size = 16)
  )
ggsave("~/Downloads/equivalence_flow.png", dpi=500, height = unit(3, "in"), width = unit(4, "in"))
```

```{r, fig.height = 2, fig.width = 6}
plot_beta(fit, models = c("K5", "K6", "K7"), n_features = 200) +
  theme(
    axis.text.x = element_text(size = 16),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    panel.grid.major.y = element_blank(),
    strip.text = element_text(size = 18)
  ) +
  scale_size(range = c(0, 35), limits = c(0, 1))
ggsave("~/Downloads/equivalence_betas.png", dpi=750)
```

```{r}
model_sims <- similarities %>%
  filter(
    file == "similarities-transport_230_12_250_1000_5.csv",
    m %in% str_c("K", 5:7)
  ) %>%
  group_by(m) %>%
  mutate(
    k_LDA = as.factor(row_number()),
  ) %>%
  pivot_longer(starts_with("V"), names_to = "truth", values_to = "similarity") %>%
  mutate(truth = gsub("V", "", truth))

ggplot(model_sims) +
  geom_tile(aes(k_LDA, truth, fill = similarity)) +
  scale_x_discrete(expand = c(0, 0)) +
  scale_y_discrete(expand = c(0, 0)) +
  facet_grid(~ m, scale = "free_x", space = "free") +
  labs(
    x = expression(paste("Fitted Topic ", hat(beta)[k])),
    y = expression(paste("Topic ", beta[k])),
    fill = expression(paste("cossim(", beta[k], ", ", hat(beta)[k], ")"))
    ) +
  scale_fill_stepsn(
    breaks = c(0.35, 0.7, 0.9, 0.95),
    colors = c("#662539", "#913551", "#c66281", "#c0d9e5", "#96bfd4", "#478bae"),
    values = c(0, 0.35, 0.7, 0.9, 0.95, 1)
  ) +
  theme(
    strip.text = element_text(size = 16),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 17),
    legend.text = element_text(size = 8),
    legend.title = element_text(size = 14),
  )
ggsave("~/Downloads/equivalence_similarity_hm.png", dpi=500, width = unit(7, "in"), height = unit(4, "in"))
```

```{r}
diffs <- similarities %>%
  separate(file, c("method", "S", "id", "N", "V", "K"), "_", remove = FALSE) %>%
  mutate(
    method = gsub("similarities-", "", method),
    D1 = V1 - V2, D2 = V3 - V4,
    S = as.integer(S)
  ) %>%
  group_by(m, method, S, id, rep) %>%
  summarise(DTotal = mean(abs(V1 - V2) + abs(V3 - V4)))

ggplot(diffs, aes(S, DTotal)) +
  geom_smooth(method = "lm", col = "#5d3954") +
  geom_point(alpha = 0.6, size = 0.3) +
  facet_grid(method ~ m) +
  labs(x = "Perturbation Subset Size", y = "Estimation Sensitivity") +
  theme(
    strip.text = element_text(size = 16),
    axis.text.y = element_text(size = 14),
    axis.text.x = element_text(size = 7),
    axis.title = element_text(size = 17)
    )
ggsave("~/Downloads/equivalence_similarities.png", dpi = 500)
```

```{r, message = FALSE}
paths <- list.files(equiv_dir, "perplexity*", full = TRUE)
perplexity <- map_dfr(paths, ~ read_csv(.), .id = "path") %>%
  mutate(perplexity, path = paths[as.integer(path)])
ggplot(perplexity, aes(K, perplexity)) +
  geom_point(alpha = 0.1, position = position_jitter(w = 0.2))
ggsave("~/Downloads/switching-perplexity.png", dpi = 400)
```
