---
title: "Visualize Results"
output: html_notebook
params:
    results_dir: "results/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, message = FALSE, warning = FALSE, fig.width = 5, fig.height = 2)
```

```{r}
library(alto)
library(dplyr)
library(ggplot2)
library(readr)
library(tibble)
library(purrr)
library(stringr)
library(tidyr)
source("https://raw.githubusercontent.com/krisrs1128/topic_align/main/simulations/simulation_functions.R")
my_theme()
```

### True LDA Experiment

The simulation results we're working with are saved here:
https://uwmadison.box.com/shared/static/accan0ji43d7l97bia2fa9ai5zu826xm.gz

First, we plot a random flow.

```{r, fig.height = 3, fig.width = 5}
lda_dir <- file.path(params$results_dir, "lda")
fits <- list(
  get(load(file.path(lda_dir, "exper-product_2_250_1000_5.rda")))[2],
  get(load(file.path(lda_dir, "exper-transport_2_250_1000_5.rda")))[2]
)
plot(fits[[1]][[1]]) +
  labs(x = "K Topics") +
  theme(axis.text.y = element_blank())
ggsave("~/Downloads/product-true-lda.png", dpi=500)
plot(fits[[2]][[1]]) +
  labs(x = "K Topics") +
  theme(axis.text.y = element_blank())
ggsave("~/Downloads/transport-true-lda.png", dpi=500)
```

```{r, fig.height = 4, fig.width = 6}
png("~/Downloads/product-true-lda-betas.png", width = 1000, height = 500)
plot_beta(fits[[1]][[1]], models = 2:10, legend = FALSE, bottom.label.text.size = 14, left.label.text.size = 8, yr.axis.name.size = 14, yr.axis.size = 12)
dev.off()
png("~/Downloads/transport-true-lda-betas.png", width = 1000, height = 500)
plot_beta(fits[[2]][[1]], models = 2:10, legend = FALSE, bottom.label.text.size = 14, left.label.text.size = 8, yr.axis.name.size = 14, yr.axis.size = 12)
dev.off()
```


Now, we plot the stability curves.

```{r}
read_and_process <- function(pattern, grouping, directory, max_K=10) {
  paths <- list.files(directory, pattern, full = TRUE)
  map_dfr(paths, read_csv, .id = "file") %>%
    suppressMessages() %>%
    mutate(
      m = factor(m, levels = str_c("K", 1:max_K)),
      file = basename(paths[as.integer(file)]),
      method = ifelse(grepl("product", file), "product", "transport")
    ) %>%
    unite("group", grouping, remove = FALSE)
}
```

```{r}
#paths <- list.files("results/lda", "exper*", full = TRUE)

read_betas <- function(paths) {
  betas <- list()
  beta_hats <- list()
  for (i in seq_along(paths)) {
    exper <- get(load(paths[i]))
    beta_hats[[i]] <- map_dfr(model(exper[[2]]), ~ .$beta, .id = "m") %>%
      mutate(sim = i)
    betas[[i]] <- map_dfr(exper[[1]]$beta, ~ .$beta, .id = "m") %>%
      mutate(sim = i)
  }
  
  list(
    beta_hats = bind_rows(beta_hats),
    betas = bind_rows(betas)
  )
}


estimate_similarities <- function(betas, beta_hats) {
  # for each simulation replicate
  # for each estimated beta_hat among the fitted models
  max_sim <- apply(betas[[i]] %*% t(beta_hats[[i]]), 1, max)
}
```

```{r}
stability <- read_and_process("stability*", c("id", "branch", "method"), lda_dir)
```

Notice there are few new branches that begin after K5, and those that do decay
quite quickly.

```{r, fig.width = 6, fig.height = 3}
ggplot(stability) +
  geom_line(aes(m, stability, group = group), alpha = 0.2, size = 0.2) +
  facet_grid(. ~ method)
```


```{r, fig.width = 10, fig.height = 3}
ggplot(stability %>% filter(id < 10)) +
  geom_line(aes(m, stability, group = group), alpha = 0.4, size = 0.8) +
  facet_wrap(~ id, ncol = 5)
```


```{r}
key_topics <- read_and_process("key*", c("id"), file.path(params$results_dir, "lda"))
ggplot(key_topics) +
  geom_line(aes(x = m, y = n_key_topics, group = id), alpha = 0.6)
```

```{r, fig.width = 5, fig.height = 3}
key_counts <- key_topics %>%
  group_by(m, method) %>%
  count(n_key_topics) %>%
  filter(m != "K10")

ggplot(key_counts) +
  geom_hline(yintercept = 5) +
  geom_point(aes(x = m, y = n_key_topics, size = n)) +
  labs(x = "K Topics", y = "Key Topics") +
  facet_wrap(~ method)
ggsave("~/Downloads/key_topics-lda.png", dpi=500)
```

```{r, fig.width = 5, fig.height = 3}
offset_up <- key_topics %>%
  group_by(id) %>%
  slice_max(n_topics, n = 8) %>%
  arrange(id, n_topics) %>%
  rename(m_next = m, n_key_topics_next = n_key_topics) %>%
  ungroup() %>%
  select(m_next, n_key_topics_next)

offset_down <- key_topics %>%
  group_by(id) %>%
  slice_min(n_topics, n = 8) %>%
  arrange(id, n_topics) %>%
  ungroup()

key_counts <- bind_cols(offset_down, offset_up) %>%
  count(m, m_next, n_key_topics, n_key_topics_next)
```

```{r, fig.width = 5, fig.height = 3}
ggplot(key_counts %>% filter(m_next != "K10")) +
  geom_segment(aes(m, n_key_topics, xend = m_next, yend = n_key_topics_next, size = n, alpha = n)) +
  geom_hline(yintercept = 5) +
  scale_size(range = c(0.5, 2)) +
  scale_alpha(range = c(0.2, 1))
```

```{r}
refinement <- read_and_process("*refinement*", c("id"), lda_dir)
ggplot(refinement) +
  geom_point(
    aes(m, refinement_score),
    position = position_jitter(w = 0.1),
    alpha = 0.1, size = 0.2
  ) +
  scale_y_log10()
```
```{r}
ggplot(refinement) +
  geom_violin(
    aes(m, refinement_score)
  ) +
  scale_y_log10() +
  labs(x = "K Topics", y = "refinement") +
  facet_wrap(~ method, scale = "free_y")
ggsave("~/Downloads/refinement_lda.png", dpi=500)
```

#### Gradient Experiment

```{r}
gradient_dir <- file.path(params$results_dir, "gradient")
stability <- read_and_process("stability*", c("branch", "file"), gradient_dir) %>%
  separate(file, c("method", "alpha", "id", "N", "V", "K"), "_", remove = FALSE) %>%
  mutate(
    across(alpha:K, as.numeric),
    method = gsub("stability-", "", method)
  ) 
```

```{r, fig.width = 8, fig.height = 3.5}
subset_alpha <-  c(0, 0.2, 0.4, 0.6, 0.8, 1)
ggplot(stability %>% filter(alpha %in% subset_alpha)) +
  geom_line(aes(m, stability, col = alpha, group = group), alpha = 0.2, size = 0.5) +
  scale_color_viridis_c(breaks = c(0, 0.5, 1)) +
  scale_y_continuous(breaks = c(0, 0.5, 1)) +
  facet_grid(method ~ alpha) +
  labs(col = expression(alpha), x = "K Topics") +
  theme(axis.text.x = element_text(size = 6))
ggsave("~/Downloads/gradient_stability.png", dpi = 500)
```
```{r, fig.width = 5, fig.height = 3}
ggplot(stability) +
  geom_line(aes(m, stability, group = group, col = alpha), alpha = 0.2, size = 0.3) +
  scale_color_viridis_c()
```

```{r}
key_topics <- read_and_process("key*", c("file"), gradient_dir) %>%
  separate(file, c("tmp", "method", "alpha", "id", "N", "V", "K"), "_", remove = FALSE) %>%
  mutate(across(alpha:V, as.numeric))
```

```{r, fig.width = 5, fig.height = 3}
key_counts <- key_topics %>%
  group_by(m, alpha, method) %>%
  count(n_key_topics) %>%
  mutate(method = gsub("topics-", "", method))

ggplot(key_counts) +
  geom_hline(yintercept = 5) +
  geom_point(
    aes(m, n_key_topics, col = alpha, size = n),
    alpha = 0.4, position = position_jitter(w = 0.1, h = 0.1)
  ) +
  scale_size(range = c(0, 3)) +
  scale_color_viridis_c() +
  facet_wrap(~ method)
```


```{r, fig.width = 8, fig.height = 4}
ggplot(key_counts %>% filter(m != "K10", alpha %in% subset_alpha)) +
  geom_hline(yintercept = 5) +
  geom_point(aes(m, n_key_topics, col = alpha, size = n)) +
  scale_color_viridis_c(breaks = c(0, 0.5, 1)) +
  scale_size(range = c(0, 3)) +
  labs(x = "Fitted Topics", y = "Key Topics", col = expression(alpha)) +
  facet_grid(method ~ alpha) +
  theme(axis.text.x = element_text(size = 7))
ggsave("~/Downloads/gradient_key_topics.png", dpi = 500)
```

```{r}
refinement <- read_and_process("refinement*", c("file"), gradient_dir) %>%
  separate(file, c("method", "alpha", "id", "N", "V", "K"), "_", remove = FALSE) %>%
  mutate(
    across(alpha:V, as.numeric),
    method = gsub("refinement-", "", method)
  )
```

```{r, fig.height = 3, fig.width = 5}
ggplot(refinement %>% filter(m != "K10")) +
  geom_point(
    aes(m, refinement_score, col = alpha),
    position = position_jitter(w = 0.1),
    alpha = 0.1, size = 0.2
  ) +
  scale_color_viridis_c() +
  scale_y_log10() +
  facet_wrap(~ method)
```

```{r, fig.height = 3.5, fig.width = 8}
ggplot(refinement %>% filter(m != "K10", alpha %in% subset_alpha)) +
  geom_violin(
    aes(m, refinement_score, fill = alpha)
  ) +
  facet_grid(method ~ alpha) +
  scale_fill_viridis_c(breaks = c(0, 0.5, 1)) +
  labs(y = "Refinement", x = "K Topics", fill = expression(alpha)) +
  scale_y_log10() +
  theme(axis.text.x = element_text(size = 6))
ggsave("~/Downloads/gradient_refinement_full.png", dpi = 500)
```

```{r, fig.height = 3, fig.width = 5}
paths <- c("exper-transport_0_3_250_1000_5.rda", "exper-transport_0.4_1_250_1000_5.rda", "exper-transport_0.6_10_250_1000_5.rda", "exper-transport_1_1_250_1000_5.rda")
for (s in seq_along(paths)) {
  fit <- get(load(file.path(gradient_dir, paths[s])))[[2]]
  plot(fit)
  ggsave(sprintf("~/Downloads/gradient_flow-%s.png", s), dpi = 500, height = 3, width = 5)
}
```


### Functional Equivalence

```{r}
equiv_dir <- file.path(params$results, "equivalence")
similarities <- read_and_process("*similarities*", c("rep", "S"), equiv_dir)
```

```{r, fig.width = 6, fig.height = 4}
exper <- get(load(file.path(equiv_dir, "exper-transport_230_12_250_1000_5.rda")))
sim_data <- exper[[1]]
fit <- exper[[2]]
plot(fit) +
  labs(x = "K Topics") +
  theme(axis.text.y = element_blank())
ggsave("~/Downloads/equivalence_flow.png", dpi = 500)
```

```{r, fig.height = 9, fig.width = 14}
png("~/Downloads/equivalence_betas.png", width = 1000, height = 500)
#plot_beta(fit, models = c("K5", "K6", "K7"), legend = FALSE, bottom.label.text.size = 14, left.label.text.size = 12, yr.axis.name.size = 14, yr.axis.size = 12)
plot_beta(fit, models = c("K5", "K6", "K7"), legend = FALSE, bottom.label.text.size = 14, left.label.text.size = 12, yr.axis.name.size = 14, yr.axis.size = 12)
dev.off()
```

```{r, fig.height = 3, fig.width = 8}
model_sims <- similarities %>%
  filter(
    file == "similarities-transport_230_12_250_1000_5.csv",
    m %in% str_c("K", 4:8)
  ) %>%
  group_by(m) %>%
  mutate(
    k_LDA = as.factor(row_number()),
  ) %>%
  pivot_longer(starts_with("V"), names_to = "truth", values_to = "similarity") %>%
  mutate(truth = gsub("V", "", truth))

ggplot(model_sims) +
  geom_tile(aes(k_LDA, truth, fill = similarity)) +
  scale_x_discrete(expand = c(0, 0)) +
  scale_y_discrete(expand = c(0, 0)) +
  facet_grid(~ m, scale = "free_x", space = "free") +
  labs(x = "Fitted Topic", y = "True Topic") +
  scico::scale_fill_scico(palette = "nuuk")
ggsave("~/Downloads/equivalence_similarity_hm.png", dpi=500)
```

```{r, fig.width = 10, fig.height = 4}
diffs <- similarities %>%
  separate(file, c("method", "S", "id", "N", "V", "K"), "_", remove = FALSE) %>%
  mutate(
    method = gsub("similarities-", "", method),
    D1 = V1 - V2, D2 = V3 - V4,
    S = as.integer(S)
  ) %>%
  group_by(m, method, S, id, rep) %>%
  summarise(DTotal = mean(abs(V1 - V2) + abs(V3 - V4)))

ggplot(diffs, aes(S, DTotal)) +
  geom_smooth(method = "lm", col = "#5d3954") +
  geom_point(alpha = 0.6, size = 0.3) +
  facet_grid(method ~ m) +
  labs(x = "Perturbation Subset Size", y = "Estimation Sensitivity") +
  theme(axis.text.x = element_text(size = 6))
ggsave("~/Downloads/equivalence_similarities.png", dpi = 500)
```
