---
title: "Visualize LDA with Background Noise"
output: html_notebook
params:
    results_dir: "results/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, message = FALSE, warning = FALSE, fig.width = 5, fig.height = 2)
```

```{r}
library(alto)
library(tidyverse)
source("simulation_functions.R")
source("visualization_functions.R")
my_theme()
```

The simulation results we're working with are saved
[here](https://uwmadison.box.com/shared/static/accan0ji43d7l97bia2fa9ai5zu826xm.gz).
If we download that file, unzip it, and unzip all its contents, we should see
the directories and files that are referred to in this rmarkdown. Specifically,
we could run,
```
curl -L https://uwmadison.box.com/shared/static/accan0ji43d7l97bia2fa9ai5zu826xm.gz > results.tar.gz
tar -zxvf results.gz
cd results # set this to results_dir in the rmarkdown YAML
for f in $(ls *.tar.gz); do tar -zxvf $f; done
```
in our terminal.

### Gradient Experiment

```{r}
gradient_dir <- file.path(params$results_dir, "gradient")
paths <- list.files(gradient_dir, "exper*", full = TRUE)
max_K <- 10
measures <- map_dfr(
  paths,
  ~ topics(get(load(.))[[2]]),
  .id = "file"
) %>%
  mutate(
    m = factor(m, levels = str_c("K", 1:max_K)),
    m_ix = as.numeric(str_extract(m, "[0-9]+")),
    file = basename(paths[as.integer(file)]),
    method = ifelse(grepl("product", file), "product", "transport")
  ) %>%
  separate(file, c("prefix", "alpha", "rep", "N", "D", "K"),  "_", remove = FALSE) %>%
  mutate(
    alpha = as.numeric(alpha),
    alpha = factor(alpha, levels = as.character(seq(1, 0, by = -0.1)))
  )

betas <- read_betas(paths, c(2, 1), "topics")
similarity <- topic_cossim(betas$betas, betas$beta_hats) %>%
  mutate(m = factor(m, levels = levels(measures$m)))

measures <- measures %>%
  left_join(similarity)
rm(similarity)
```


```{r}
subset_alpha <-  as.character(seq(0, 0.8, 0.2))
quantiles <- measures %>% 
  filter(m_ix != 10, m_ix != 1, alpha %in% subset_alpha) %>%
  group_by(m_ix, alpha, method) %>%
  summarize(
    q_25 = quantile(coherence, 0.25),
    q_75 = quantile(coherence, 0.75)
  )
```

```{r}
coherence_figure <- function(df, quantiles) {
  ggplot(df, aes(m_ix)) +
    geom_ribbon(
      data = quantiles, 
      aes(m_ix, ymin = q_25, ymax = q_75),
      size = 0.5,
      fill = "lightgrey"
    ) +
    geom_point(
      aes(y = coherence, col = sim),
      size = .1,
      position = position_jitter(w = 0.2)
    ) +
    scale_colour_stepsn(
      breaks = c(0.35, 0.7, 0.9, 0.95),
      colors = c("#662539", "#913551", "#c66281", "#c0d9e5", "#96bfd4", "#478bae"),
      values = c(0, 0.35, 0.7, 0.9, 0.95, 1)
    ) +
    scale_x_continuous(labels = scales::label_number(accuracy = 1)) +
    labs(
      x = "K Topics", 
      y = "Coherence",
      col = expression(paste(max[k], "cossim(", beta[k], ", ", hat(beta), ")"))
    ) +
    facet_grid(alpha ~ method) +
    theme(
      strip.text = element_text(size = 15),
      axis.text.y = element_text(size = 10),
      axis.text.x = element_text(size = 10),
      axis.title = element_text(size = 15),
      panel.grid.major.x = element_blank(),
      legend.position = "none"
    )
}

figures <- list()
figures[["coherence_alpha_1"]] <-  measures %>% 
  filter(m_ix != 10, m_ix != 1, alpha == "1") %>%
  coherence_figure(quantiles %>% filter(alpha == "1")) +
  ggtitle("b")
figures[["coherence_alpha_noise"]] <-  measures %>% 
  filter(m_ix != 10, m_ix != 1, alpha %in% subset_alpha) %>%
  coherence_figure(quantiles %>% filter(alpha != "1")) +
  ggtitle("e")
```


```{r}
key_topics <- read_and_process("key*", c("file"), gradient_dir) %>%
  separate(file, c("tmp", "method", "alpha", "id", "N", "V", "K"), "_", remove = FALSE) %>%
  mutate(across(alpha:V, as.numeric))
```

```{r}
key_counts <- key_topics %>%
  group_by(m, alpha, method) %>%
  count(n_paths) %>%
  mutate(
    method = str_remove(method, "topics-"),
    m = as.integer(str_remove(as.character(m), "K")),
    alpha = factor(alpha, levels = seq(1, 0, by = -0.1))
  )
```

```{r}
paths_figure <- function(df) {
  ggplot(df %>% filter(m != "K10")) +
    geom_hline(yintercept = 5) +
    geom_point(aes(m, n_paths, size = n)) +
    scale_size(range = c(0, 3)) +
    labs(
      x = "K Topics", 
      y = "Number of Paths", 
      col = expression(alpha),
      size = "N Simulations"
    ) +
    scale_x_continuous(labels = scales::label_number(accuracy = 1)) +
    scale_y_continuous(breaks = c(2, 5, 8)) +
    facet_grid(alpha ~ method) +
    theme(
      axis.text.x = element_text(size = 5),
      axis.text.y = element_text(size = 9),
      axis.title = element_text(size = 16),
      strip.text = element_text(size = 16),
      legend.title = element_text(size = 14),
      legend.text = element_text(size = 10)
    )
}

figures[["paths_alpha_1"]] <- key_counts %>%
  filter(alpha == "1") %>%
  paths_figure() +
  ggtitle("a")
figures[["paths_alpha_noise"]] <- key_counts %>%
  filter(alpha %in% subset_alpha) %>%
  paths_figure() + 
  ggtitle("d")
```

```{r}
quantiles <- measures %>% 
  filter(m_ix != 10, m_ix != 1, alpha %in% subset_alpha) %>%
  group_by(m_ix, alpha, method) %>%
  summarize(
    q_25 = quantile(refinement, 0.25),
    q_75 = quantile(refinement, 0.75)
  )
```


```{r}
refinement_figure <- function(measures, quantiles) {
  ggplot(measures %>% filter(m_ix != 10), aes(m_ix)) +
  geom_ribbon(
    data = quantiles, 
    aes(m_ix, ymin = q_25, ymax = q_75),
    size = 0.5,
    fill = "lightgrey"
  ) +
  geom_point(
    aes(y = refinement, col = sim),
    size = .1,
    position = position_jitter(w = 0.2)
  ) +
  scale_colour_stepsn(
    breaks = c(0.35, 0.7, 0.9, 0.95),
    colors = c("#662539", "#913551", "#c66281", "#c0d9e5", "#96bfd4", "#478bae"),
    values = c(0, 0.35, 0.7, 0.9, 0.95, 1)
  ) +
  scale_x_continuous(labels = scales::label_number(accuracy = 1)) +
  labs(
    x = "K Topics", 
    y = "Refinement",
    col = expression(paste(max[k], "cossim(", beta[k], ", ", hat(beta), ")"))
  ) +
  facet_grid(alpha ~ method, scale = "free_y") +
  theme(
    strip.text = element_text(size = 15),
    axis.text.y = element_text(size = 10),
    axis.text.x = element_text(size = 10),
    axis.title = element_text(size = 15),
    panel.grid.major.x = element_blank()
  )
}

figures[["refinement_alpha_1"]] <- measures %>%
  filter(alpha == "1") %>%
  refinement_figure(quantiles %>% filter(alpha == "1")) +
  theme(legend.position = "none") +
  ggtitle("c")

figures[["refinement_alpha_noise"]] <- measures %>%
  filter(alpha %in% subset_alpha) %>%
  refinement_figure(quantiles %>% filter(alpha %in% subset_alpha)) +
  ggtitle("e")
```

```{r, fig.height = 3, fig.width = 5}
paths <- c("exper-transport_0_3_250_1000_5.rda", "exper-transport_0.4_1_250_1000_5.rda", "exper-transport_0.6_10_250_1000_5.rda", "exper-transport_1_1_250_1000_5.rda")
for (s in seq_along(paths)) {
  fit <- get(load(file.path(gradient_dir, paths[s])))[[2]]
  plot(fit)
  ggsave(sprintf("~/Downloads/gradient_flow-%s.png", s), dpi = 500, height = 3, width = 5)
}
```

```{r, message = FALSE, fig.width=8, fig.height=5}
paths <- list.files(gradient_dir, "perplexity*", full = TRUE)
perplexity <- map_dfr(paths, ~ read_csv(.), .id = "path") %>%
  suppressMessages() %>%
  pivot_longer(train:test, "split", values_to="perplexity") %>%
  mutate(perplexity, path = basename(paths[as.integer(path)])) %>%
  separate(path, c("prefix", "alpha", "rep", "N", "D", "K_"),  "_", remove = FALSE)
```

```{r, message = FALSE, fig.width=8, fig.height=2.5}
ggplot(perplexity %>% filter(alpha %in% subset_alpha)) +
  geom_line(aes(K, perplexity, group = interaction(path, split), col = split), alpha = 0.2, size = .8) +
  labs(x = "K", y = "perplexity") +
  scale_color_manual(values = c("#83A638", "#F2780C")) +
  guides(col = guide_legend(override.aes = list(size = 3, alpha = 1))) +
  facet_wrap(~ alpha, ncol = 6)
ggsave("~/Downloads/gradient-perplexity.png", dpi = 400, width = 7.5, height = 3)
```
```{r, fig.height = 9, fig.width= 8}
library(patchwork)
(figures[["paths_alpha_1"]] + figures[["coherence_alpha_1"]] + figures[["refinement_alpha_1"]]) /
(figures[["paths_alpha_noise"]] + figures[["coherence_alpha_noise"]] + figures[["refinement_alpha_noise"]]) +
  plot_layout(height = c(1, 5), guides = "collect")
ggsave("~/Downloads/gradient-combined.png", height = 10, width = 9)
```
