#!/bin/bash

wget https://uwmadison.box.com/shared/static/cfkmr6jy8v23ftvdbqqxc27dscgoavas.gz
mv cfkmr6jy8v23ftvdbqqxc27dscgoavas.gz alto.tar.gz
tar -zxvf alto.tar.gz
Rscript -e "library(devtools); install('alto')"
